config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :posts do
    member do
      get "like", to: "posts#upvote"
      get "dislike", to: "posts#downvote"
    end
    resources :comments
    
  end
  
  root 'posts#index'
  
  get '/aa/', to: 'posts#aa'
  get '/about', to: 'pages#about'
  get '/pages/japan' => 'pages#japan'
  get '/pages/taiwan' => 'pages#taiwan'
  get '/pages/country' => 'pages#country'
  get '/public/404' => 'public#404'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  
end

app/models/post.rb
class Post < ActiveRecord::Base
    acts_as_votable
    has_many :comments, dependent: :destroy
    # validates :subject_code, presence: true
    # validates :subject_name, presence: true
    validates :option, presence: true
    # validates :lecturer, presence: true
    validates :content, presence: true
    # validates :rating, presence: true
    
    def self.search(search)
      where("subject_name LIKE ?", "%#{search}%")
      where("subject_code LIKE ?", "%#{search}%")
      where("lecturer LIKE ?", "%#{search}%")
      where("content LIKE ?", "%#{search}%")
    end
    
    
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    
    def create
        @post = Post.find(params[:post_id])
        @comment = @post.comments.create(params[:comment].permit(:body))
        
        redirect_to post_path(@post)
    end
    
    def destroy
        @post = Post.find(params[:post_id])
        @comment = @post.comments.find(params[:id])
        @comment.destroy
        
        redirect_to post_path(@post)
    end
    
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    
    def about
    
    end
    
    def japan
        
    end
    
    def taiwan
        
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :find_post, only: [:edit, :update, :destroy, :upvote, :downvote]
    before_action :authenticate_user!, except: [:index, :show]

    
    def index
        
	    unless user_signed_in?
		    redirect_to "/users/sign_in"
	    end        

        if params[:search]
            @posts = Post.search(params[:search]).order('created_at DESC').paginate(page: params[:page], per_page: 5)

        else
            @posts = Post.all.order('created_at DESC').paginate(page: params[:page], per_page: 5)
            
        end

    end

    def suspect
    end
    
    def country
       @post=Post.country
    end
    
    def new
        @post = Post.new
    end 
    
    def create
        @post = Post.new(post_params)
        if @post.save
            redirect_to @post
        else
            render 'new'
        end    
    end
    
    def show
        @post = Post.find(params[:id])
        
    end
    
    def edit
       @post = Post.find(params[:id]) 
    end
    
    def update
        @post = Post.find(params[:id])
        
        if @post.update(params[:post].permit(:option, :subject_code, :subject_name, :lecturer, :rating, :content))
            redirect_to @post
        else
            render 'edit'
        end
    end
    
    def destroy
        @post = Post.find(params[:id])
        @post.destroy
        
        redirect_to root_path
    end
    
    def upvote 
        @post.upvote_by current_user
        redirect_to :back
    end

    def downvote 
        @post.downvote_by current_user
        redirect_to :back
    end
    
    def find_post
        @post = Post.find(params[:id])
    end
    
    def aa
    end
    
    private
        def post_params
            params.require(:post).permit(:option, :subject_code, :subject_name, :lecturer, :rating, :content)
        end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/time.rb
 module TimeHelper
   def timeago(time, options = {})
     options[:class] ||= "timeago"
     content_tag(
       :time,
       time.to_s,
       options.merge(datetime: time.getutc.iso8601)
     ) if time
   end
 end

app/views/comments/_comment.html.erb
<div class="comment clearfix">
	<div class="comment_content">
	 <p>
        <div class="star-rating" data-score= <%= @post.rating %> ></div>
    </p>
    <br>
		<p class="comment_body"><%= comment.body %></p>
		<!--<p class="comment_time"><%#= time_ago_in_words(comment.created_at) %> Ago</p>-->
	</div>
	
	<% if user_signed_in? %>
    	<p><%= link_to 'Delete', [comment.post, comment],
    	               method: :delete,
    	               class: "button",
    	               data: { confirm: '댓글을 삭제하시겠습니까?' } %>
    	</p>
    <% end %>



</div>

<script>
    $('.star-rating').raty({
        path: '/assets/',
        readOnly: true,
        score: function() {
            return $(this).attr('data-score');
        }
    });
    
</script>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>
    <p>
        <%= f.label :comment %><br>
        <%= f.text_field :body %>
    </p>
         <p>
        <%= f.label :별점 %><br>
        <div id="star-rating"></div>
    </p><br>
    </p>
    </p><br>
    <p>
        <%= f.submit %>
    </p>
 
<% end %>

<script>
    $('#star-rating').raty({
        path: '/assets/',
        scoreName: 'post.rating'
    });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>건양대 교양평가 서비스</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'application', 'http://fonts.googleapis.com/css?family=Raleway:400,700' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= csrf_meta_tags %>

  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
	
  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">
	
  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>  

  
</head>
<body>
	<div id="sidebar">
		<div id="logo">
			<%= link_to root_path do %>
				<%= image_tag "logo.svg" %>
			<% end %>
		</div>

		<ul>
			<li class="category">about</li>
			<li><strong><%= link_to "소개", about_path %></strong></li>
		</ul>
		
		<ul>
			<li class="category">게시판 서비스</li>
			<li><strong><%= link_to "교양평가 게시판", root_path %></strong></li>
			<!--
			<li><strong><a href="#">자유게시판</a></strong></li>
			<li><strong><a href="#">중고장터</a></strong></li>
			<li><strong><a href="#">익명게시판</a></strong></li>
			!-->

		</ul>

	</div>
	
	<div id="main_content">
	  <div id="header">
	  	<% if current_page?(root_path) %>
		    <p>All Posts</p>
		  <% elsif current_page?(about_path) %>
		  	<p>About</p>
		  <% else %>
		  	<%= link_to "Back to All Posts", root_path %>
		  <% end %>
		  
		  <p class="sign_in"><%= link_to "Login", new_user_session_path %></p>
		  
			<% if user_signed_in? %>
		    <div class="buttons">
		      <button class="button"><%= link_to "New Post", new_post_path %></button>
		      <button class="button"><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></button>
		    </div>
		    
		  <% end %>
	  </div>
    <% flash.each do |name, msg| %>
      <%= content_tag(:div, msg, class: "alert") %>
    <% end %>

  	<%= yield %>	  
	</div>

</body>
</html>

app/views/pages/about.html.erb
<div id="page_wrapper">
	<div id="profile_image">
		
	</div>

	<div id="content">
		<h1>전세계 여행지 추천 사이트</h1><br>
		<h3>최고의 여행지를 추천해 드립니다!.</h3>
		<%= image_tag "https://mblogthumb-phinf.pstatic.net/20160806_181/allstar137_1470415324126Vcrrv_PNG/635845887915208016.png?type=w2" %><br><br>
		<p>....................................</p>
		<br>
		
	</div>
</div>

app/views/pages/country.html.erb
<!DOCTYPE html>
<html>
<head>
	
	<style>
		
		body {background-image:url("");
background-attachment: fixed; 
background-repeat: yes-repeat; 
background-position:bottom right;
background-size:cover;} 
	</style>
  <title>BroadMarker</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'application', 'http://fonts.googleapis.com/css?family=Raleway:400,700' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= csrf_meta_tags %>

  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
	
  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">
	
  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>  

</head>
<body>
	<div id="sidebar">
		<div id="logo">
			<%= link_to root_path do %>
				<%= image_tag "logo.svg" %>
			<% end %>
		</div>

		<ul>
			<li><strong><%= link_to "일본", pages_japan_path %></strong></li>
		</ul>	
	<ul>
			<li><strong><%= link_to "대만", pages_taiwan_path %></strong></li>
		</ul>
		<ul>
	
		
			<!--
			<li><strong><a href="#">자유게시판</a></strong></li>
			<li><strong><a href="#">중고장터</a></strong></li>
			<li><strong><a href="#">익명게시판</a></strong></li>
			!-->

		</ul>

	</div>
	
	<div id="main_content">
	  <div id="header">
	  	<% if current_page?(root_path) %>
		    <p>일본 여행지</p>
		  <% elsif current_page?(about_path) %>
		  	<p>About</p>
		  <% else %>
		  	<%= link_to "Back to All Posts", root_path %>
		  <% end %>
		  
		  <p class="sign_in"><%= link_to "Login", new_user_session_path %></p>
		  
			<% if user_signed_in? %>
		    <div class="buttons">
		      <button class="button"><%= link_to "New Post", new_post_path %></button>
		      <button class="button"><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></button>
		    </div>
		    
		  <% end %>
	  </div>
    <% flash.each do |name, msg| %>
      <%= content_tag(:div, msg, class: "alert") %>
    <% end %>

  	<%= yield %>	  
	</div>

</body>
</html>

app/views/pages/japan.html.erb
<!doctype html>
<html>
  <h1 style="color: #ff3535">Japan HOT COURSE</h1>
  <head>
   	<style>
		
		body {background-image:url("");
background-attachment: fixed; 
background-repeat: yes-repeat; 
background-position:bottom right;
background-size:cover;} 
	</style>
  <title>BroadMarker</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'application', 'http://fonts.googleapis.com/css?family=Raleway:400,700' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= csrf_meta_tags %>

  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
	
  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">
	
  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>  


	<meta charset="utf-8" />
	<title>BroadMarker_Japan_Hot Course</title>
	<script src="http://code.jquery.com/jquery-latest.min.js"></script>
	<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false"></script>
</head>








<SCRIPT LANGUAGE="JavaScript">
<!--
var contentArray = [];
var iConArray = [];
var markers = [];
var iterator = 0;
var markerArray = [];
var map;

// infowindow contents 배열
 contentArray[0] = "나고야성";
 contentArray[1] = "도쿄 디즈니랜드";
 contentArray[2] = "일본 세토대교";
 contentArray[3] = "하우스 텐보스";
 contentArray[4] = "도쿄타워";
 contentArray[5] = "유니버셜 스튜디오";
 contentArray[6] = "나라공원";
 contentArray[7] = "도고온천";
 contentArray[8] = "슈리성";
 contentArray[9] = "후지산";

// marker icon 배열
 iConArray[0] = "http://maps.google.com/mapfiles/ms/micons/yellow-dot.png";
 iConArray[1] = "http://maps.google.com/mapfiles/ms/micons/yellow-dot.png";
 iConArray[2] = "http://maps.google.com/mapfiles/ms/micons/yellow-dot.png";
 iConArray[3] = "http://maps.google.com/mapfiles/ms/micons/yellow-dot.png";
 iConArray[4] = "http://maps.google.com/mapfiles/ms/micons/yellow-dot.png";
 iConArray[5] = "http://maps.google.com/mapfiles/ms/micons/yellow-dot.png";
 iConArray[6] = "http://maps.google.com/mapfiles/ms/micons/yellow-dot.png";
 iConArray[7] = "http://maps.google.com/mapfiles/ms/micons/yellow-dot.png";
 iConArray[8] = "http://maps.google.com/mapfiles/ms/micons/yellow-dot.png";
 iConArray[9] = "http://maps.google.com/mapfiles/ms/micons/yellow-dot.png";



markerArray[0] = new google.maps.LatLng(35.1915338,136.8577571);
markerArray[1] = new google.maps.LatLng(35.6176119,139.8531201);
markerArray[2] = new google.maps.LatLng(34.3986605,133.8040771);
markerArray[3] = new google.maps.LatLng(33.0858841,129.7760338);
markerArray[4] = new google.maps.LatLng(35.6570253,139.7147318);
markerArray[5] = new google.maps.LatLng(34.6654448,135.4292731);
markerArray[6] = new google.maps.LatLng(34.6858182,135.8373699);
markerArray[7] = new google.maps.LatLng(33.8508191,132.7762294);
markerArray[8] = new google.maps.LatLng(26.2166624,127.7153856);
markerArray[9] = new google.maps.LatLng(35.3389102,138.5217106);

function initialize() {
	var mapOptions = {
		zoom: 7,
		mapTypeId: google.maps.MapTypeId.ROADMAP,
		center: new google.maps.LatLng(34.36354,135.004181)
	};

	map = new google.maps.Map(document.getElementById('map'),mapOptions);

	for (var i = 0; i < markerArray.length; i++) {
		addMarker();
	}
}


// 마커 추가
function addMarker() {

	var marker = new google.maps.Marker({
		position: markerArray[iterator],
		map: map,
		draggable: false,
		icon: iConArray[iterator]
	});
	markers.push(marker);

	var infowindow = new google.maps.InfoWindow({
      content: contentArray[iterator]
	});

	google.maps.event.addListener(marker, 'click', function() {
		infowindow.open(map,marker);
	});
	iterator++;
}

google.maps.event.addDomListener(window, 'load', initialize);
//-->
</SCRIPT>
<body>


<div id="map" style="position: absolute;width: 800px;height: 400px;z-index: 15;top: 50%;left: 26%;margin: -100px 0 0 -150px;"></div>

	<div id="sidebar">
		<div id="logo">
			<%= link_to root_path do %>
				<%= image_tag "logo.svg" %>
			<% end %>
		</div>

		<ul>
			<li><strong><%= link_to "일본", pages_japan_path %></strong></li>
		</ul>
		<ul>
			<li><strong><%= link_to "대만", pages_taiwan_path %></strong></li>
		</ul>
		<ul>
	
		


</body>
</html>

app/views/pages/taiwan.html.erb
<!doctype html>
<html>
  <h1 style="color: red">Taiwan HOT COURSE</h1>
  <head>


	<meta charset="utf-8" />
	<title>BroadMarker_Taiwan_Hot Course</title>
	<script src="http://code.jquery.com/jquery-latest.min.js"></script>
	<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false"></script>
</head>
<SCRIPT LANGUAGE="JavaScript">
<!--
var contentArray = [];
var iConArray = [];
var markers = [];
var iterator = 0;
var markerArray = [];
var map;

// infowindow contents 배열
 contentArray[0] = "지우펀";
 contentArray[1] = "국립고궁박물관";
 contentArray[2] = "미라마 엔터테이먼트 파크";
 contentArray[3] = "스린야시장";
 contentArray[4] = "훙마오청";
 contentArray[5] = "용산사";
 contentArray[6] = "중정기념당";
 contentArray[7] = "타이베이 시립동물원";
 contentArray[8] = "즈난궁";
 contentArray[9] = "얼얼바 평화 기념공원";

// marker icon 배열
 iConArray[0] = "http://maps.google.com/mapfiles/ms/micons/yellow-dot.png";
 iConArray[1] = "http://maps.google.com/mapfiles/ms/micons/yellow-dot.png";
 iConArray[2] = "http://maps.google.com/mapfiles/ms/micons/yellow-dot.png";
 iConArray[3] = "http://maps.google.com/mapfiles/ms/micons/yellow-dot.png";
 iConArray[4] = "http://maps.google.com/mapfiles/ms/micons/yellow-dot.png";
 iConArray[5] = "http://maps.google.com/mapfiles/ms/micons/yellow-dot.png";
 iConArray[6] = "http://maps.google.com/mapfiles/ms/micons/yellow-dot.png";
 iConArray[7] = "http://maps.google.com/mapfiles/ms/micons/yellow-dot.png";
 iConArray[8] = "http://maps.google.com/mapfiles/ms/micons/yellow-dot.png";
 iConArray[9] = "http://maps.google.com/mapfiles/ms/micons/yellow-dot.png";



markerArray[0] = new google.maps.LatLng(25.10700,121.84300);
markerArray[1] = new google.maps.LatLng(25.1020737,121.5450005);
markerArray[2] = new google.maps.LatLng(25.08281,121.55756);
markerArray[3] = new google.maps.LatLng(25.08660,121.52540);
markerArray[4] = new google.maps.LatLng(25.17500,121.43300);
markerArray[5] = new google.maps.LatLng(25.0371623,121.497712);
markerArray[6] = new google.maps.LatLng(25.0338219,121.5169963);
markerArray[7] = new google.maps.LatLng(24.9963168,121.575839);
markerArray[8] = new google.maps.LatLng(24.97920,121.58700);
markerArray[9] = new google.maps.LatLng(25.0408063,121.5068522);

function initialize() {
	var mapOptions = {
		zoom: 7,
		mapTypeId: google.maps.MapTypeId.ROADMAP,
		center: new google.maps.LatLng(24.97920,121.58700)
	};

	map = new google.maps.Map(document.getElementById('map'),mapOptions);

	for (var i = 0; i < markerArray.length; i++) {
		addMarker();
	}
}


// 마커 추가
function addMarker() {

	var marker = new google.maps.Marker({
		position: markerArray[iterator],
		map: map,
		draggable: false,
		icon: iConArray[iterator]
	});
	markers.push(marker);

	var infowindow = new google.maps.InfoWindow({
      content: contentArray[iterator]
	});

	google.maps.event.addListener(marker, 'click', function() {
		infowindow.open(map,marker);
	});
	iterator++;
}

google.maps.event.addDomListener(window, 'load', initialize);
//-->
</SCRIPT>
<body>
<div id="map" style="position: absolute;width: 800px;height: 400px;z-index: 15;top: 50%;left: 26%;margin: -100px 0 0 -150px;"></div>

	<div id="sidebar">
		<div id="logo">
			<%= link_to root_path do %>
				<%= image_tag "logo.svg" %>
			<% end %>
		</div>

		<ul>
			<li><strong><%= link_to "일본", pages_japan_path %></strong></li>
		</ul>
		<ul>
			<li><strong><%= link_to "대만", pages_taiwan_path %></strong></li>
		</ul>
		<ul>
	
</body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
    <% if @post.errors.any? %>
        <div id="errors">
            <h2><%= pluralize(@post.errors.count, "error") %> prevented this post from savings</h2>
            <ul>
                <% @post.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        
        </div>
    <% end %><br>
    
    <p>
        <%= f.label :제목 %><br>
        <%= f.text_field :option %><br>
    </p><br> 

    <!--<p>-->
    <!--    <%= f.label :과목코드 %><br>-->
    <!--    <%= f.text_field :subject_code %><br>-->
    <!--</p><br>-->

    <!--<p>-->
    <!--    <%= f.label :과목이름 %><br>-->
    <!--    <%= f.text_field :subject_name %><br>-->
    <!--</p><br>-->

    <!--<p>-->
    <!--    <%= f.label :교수 %><br>-->
    <!--    <%= f.text_field :lecturer %><br>-->
    <!--</p><br>-->

    <!--<p>-->
    <!--    <%= f.label :별점 %><br>-->
    <!--    <div id="star-rating"></div>-->
    <!--</p><br>-->
 
    <p>
        <%= f.label :의견 %><br>
        <%= f.text_area :content %><br>
    </p><br>    
    
    <p>
        <%= f.submit %>
    </p>
<% end %>

<script>
    $('#star-rating').raty({
        path: '/assets/',
        scoreName: 'post[rating]'
    });
</script>

app/views/posts/edit.html.erb
<div id="page_wrapper">
    <h1>수정하기</h1>
    
    <%= render 'form' %>
</div>

app/views/posts/index.html.erb
<div class="post_wrapper">
    <%= form_tag(posts_path, :method => "get", id: "search-form") do %>
    <%= text_field_tag :search, params[:search], placeholder: "Search Posts" %>
    <%= submit_tag "Search", :name => nil %>
    <% end %>
</div>

<% if @posts.present? %>

    <% @posts.each do |post| %>
        <div class="post_wrapper">
            <h2 class="subject_name"><%= link_to post.option, post %> (<%= post.comments.count %>)</h2>
            <h3><%= post.lecturer %></h3>
            <!--<div class="star-rating" data-score= <%= post.rating %>></div>-->
            <br>
            <p class="date"><%= post.created_at.strftime("%B, %d, %Y") %></p>
            <br>
            <span class="glyphicon glyphicon-thumbs-up"> <%= post.get_upvotes.size %></span>
    <span class="glyphicon glyphicon-thumbs-down"> <%= post.get_downvotes.size %></span><br>
    
        </div>
        
    <% end %>
    
<% else %>
    <div class="post_wrapper">
        <h1><p>검색된 문자열( <strong><%= params[:search] %></strong> )이 존재하지 않습니다.</p></h1>
        <br><%= image_tag "dog.jpeg" %><br><br>
    </div>
    
<% end %>

<%= will_paginate @posts, renderer: BootstrapPagination::Rails, previous_label: "이전", next_label: "다음" %>


<!--<script>-->
<!--    $('.star-rating').raty({-->
<!--        path: '/assets/',-->
<!--        readOnly: true,-->
<!--        score: function() {-->
<!--            return $(this).attr('data-score');-->
<!--        }-->
<!--    });-->
    
<!--</script>-->

app/views/posts/show.html.erb
<div id="post_content">
    <h1 class="title">
        <%#= @post.option %>     
        <span class="glyphicon glyphicon-hand-right"></span> 
        <%= @post.option %>
    </h1><br>
    
    <!--<p class="date">-->
    <!--    Submitted <%#= time_ago_in_words(@post.created_at) %> Ago-->
    <!--    <%# if user_signed_in? %>-->
    <!--        | <%#= link_to 'Edit', edit_post_path(@post) %>-->
    <!--        | <%#= link_to 'Delete', post_path(@post), method: :delete, data: { confirm: '삭제를 하시겠습니까?' } %>-->
    <!--    <%# end %>-->
    <!--</p>-->
    
    
    <p class="body">
        <h3><%= @post.content %></h3>
    </p>
    <br>
    <!--<p>-->
    <!--    <div class="star-rating" data-score= <%= @post.rating %> ></div>-->
    <!--</p>-->
    <br>
    <span class="glyphicon glyphicon-thumbs-up"> <%= @post.get_upvotes.size %></span>
    <span class="glyphicon glyphicon-thumbs-down"> <%= @post.get_downvotes.size %></span><br>
    <span class="btn btn-default"><%= link_to "like", like_post_path(@post), method: :get %></span>
    <span class="btn btn-default"><%= link_to "dislike", dislike_post_path(@post), method: :get %></span>    
    
    <div id="comments">
        <h2><%= @post.comments.count %> Comments</h2>
         


<!--#comment보이는부분-->
        <%= render @post.comments %>
        
        <h3>Add a comment:</h3>
     
        <%= render "comments/form" %>
       
    </div>

</div>


         <script>
    $('.star-rating').raty({
        path: '/assets/',
        readOnly: true,
        score: function() {
            return $(this).attr('data-score');
        }
    });
    
</script>




<!--<script>-->
<!--    $('.star-rating').raty({-->
<!--        path: '/assets/',-->
<!--        readOnly: false,-->
<!--        score: function() {-->
<!--            return $(this).attr('data-score');-->
<!--        }-->
<!--    });-->
    
<!--</script>-->